@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "ru.mattakvshi.base.jcollection.employer.Employer#getAge()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "ru.mattakvshi.base.jcollection.employer.Employer",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_416305220 { 
   	label=mattakvshi
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_566953411 { 
   	label=base
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_2132860046 { 
   	label=Employer
	labeljust=l
	fillcolor=white
	style=filled
   
   Employer1333883017XXXgetAge0[
	label="+ getAge()"
	style=filled
	fillcolor=white
	tooltip="Employer

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_525129499 { 
   	label=Example3
	labeljust=l
	fillcolor=white
	style=filled
   
   Example3453251506XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="Example3

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_525129500 { 
   	label=Example2
	labeljust=l
	fillcolor=white
	style=filled
   
   Example2453251506XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="Example2

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_952891662 { 
   	label=Example
	labeljust=l
	fillcolor=white
	style=filled
   
   Example453251506XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="Example

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
Example2453251506XXXmain1859653459 -> Employer1333883017XXXgetAge0;
Example3453251506XXXmain1859653459 -> Employer1333883017XXXgetAge0;
Example453251506XXXmain1859653459 -> Employer1333883017XXXgetAge0;
    
}
@enduml